"""Semente do catálogo global de tecnologias.

Não pretende ser exaustiva — o catálogo cresce sozinho quando um currículo
cita algo que falta (ver tag_catalog.TagCatalog.create). O que está aqui é o
que precisa existir ANTES: os nomes que aparecem em currículo e em vaga de
tecnologia, com os apelidos que as pessoas realmente escrevem. Sem os
apelidos, "postgres" viraria uma tag separada de "PostgreSQL" no primeiro
upload, e o catálogo nasceria duplicado.

## De onde vem a lista

Das 600 tags mais usadas do Stack Overflow (API pública
api.stackexchange.com, setembro de 2026) cruzadas com anúncios reais de vaga
do mercado brasileiro — é o anúncio que diz o que pesa numa contratação:
"Spring Boot (Actuator, Security/JWT, JPA)", "Oracle e MongoDB", "Datadog",
"Jira", "Quarkus", "Testcontainers", "segmento bancário".

## Apelido junta; não pode fundir coisas diferentes

Um apelido diz "é a mesma tecnologia escrita de outro jeito". A versão
anterior usava apelido para AGRUPAR: `tdd` caía em "Testes automatizados",
`kanban` em "Scrum", `playwright` em "Cypress", `lambda` em "AWS", `datadog`
em "Observabilidade". O resultado era perfil e vaga imprecisos — quem sabe
Playwright aparecia sabendo Cypress. Agora cada uma é tag própria, e o teste
test_tag_seed garante que nenhum apelido aponta para duas tags.

`popularity` ordena o autocomplete: quanto maior, mais acima.
"""

# (nome, categoria, popularidade, apelidos)
SEED: list[tuple[str, str, int, list[str]]] = [
    # ── Linguagens ─────────────────────────────────────────────────────────
    ("JavaScript", "linguagem", 100, ["js", "ecmascript", "es6"]),
    ("TypeScript", "linguagem", 95, ["ts"]),
    ("Python", "linguagem", 95, ["py", "python3"]),
    ("Java", "linguagem", 90, ["java se", "jdk", "java 8", "java 11", "java 17", "java 21"]),
    ("C#", "linguagem", 80, ["csharp", "c sharp", "dotnet c#"]),
    ("Go", "linguagem", 70, ["golang"]),
    ("PHP", "linguagem", 70, []),
    ("Ruby", "linguagem", 60, []),
    ("Kotlin", "linguagem", 60, []),
    ("Swift", "linguagem", 55, []),
    ("Rust", "linguagem", 55, []),
    ("C++", "linguagem", 50, ["cpp", "c plus plus"]),
    ("C", "linguagem", 45, []),
    ("SQL", "linguagem", 90, ["ansi sql"]),
    ("Shell Script", "linguagem", 45, ["bash", "shell", "sh", "zsh"]),
    ("Scala", "linguagem", 35, []),
    ("Dart", "linguagem", 40, []),
    ("R", "linguagem", 35, ["linguagem r", "r language"]),
    ("Elixir", "linguagem", 25, []),
    ("Groovy", "linguagem", 20, []),
    ("PowerShell", "linguagem", 30, []),
    ("VBA", "linguagem", 20, ["excel vba"]),
    ("COBOL", "linguagem", 20, ["mainframe cobol"]),
    ("PL/SQL", "linguagem", 40, ["plsql", "pl sql"]),
    ("T-SQL", "linguagem", 30, ["tsql", "transact-sql"]),
    # ── Frontend ───────────────────────────────────────────────────────────
    ("React", "frontend", 100, ["react.js", "reactjs", "react js"]),
    ("Next.js", "frontend", 80, ["nextjs"]),
    ("Vue.js", "frontend", 70, ["vue", "vuejs", "vue 3"]),
    ("Angular", "frontend", 70, ["angular 2+", "angular 15", "angular 17"]),
    ("AngularJS", "frontend", 25, ["angular.js", "angular 1"]),
    ("Svelte", "frontend", 40, ["sveltekit"]),
    ("HTML", "frontend", 90, ["html5"]),
    ("CSS", "frontend", 90, ["css3"]),
    ("Sass", "frontend", 55, ["scss"]),
    ("Tailwind CSS", "frontend", 65, ["tailwind", "tailwindcss"]),
    ("Bootstrap", "frontend", 45, ["twitter bootstrap"]),
    ("Material UI", "frontend", 35, ["mui", "angular material"]),
    ("Redux", "frontend", 55, ["redux toolkit"]),
    ("RxJS", "frontend", 35, []),
    ("NgRx", "frontend", 25, []),
    ("React Query", "frontend", 30, ["tanstack query"]),
    ("Zustand", "frontend", 20, []),
    ("jQuery", "frontend", 30, ["jquery ui"]),
    ("Vite", "ferramenta", 50, []),
    ("Webpack", "ferramenta", 45, []),
    ("Acessibilidade", "frontend", 40, ["a11y", "wcag"]),
    ("Microfrontends", "frontend", 30, ["micro frontends", "micro-frontends", "module federation"]),
    ("Storybook", "frontend", 25, []),
    ("PWA", "frontend", 25, ["progressive web app"]),
    ("Figma", "ferramenta", 40, []),
    ("UX/UI", "frontend", 35, ["ux", "ui design", "ux design"]),
    # ── Backend e frameworks ──────────────────────────────────────────────
    ("Node.js", "backend", 90, ["node", "nodejs", "node js"]),
    ("Express", "backend", 65, ["express.js", "expressjs"]),
    ("NestJS", "backend", 50, ["nest.js", "nest"]),
    ("Spring Boot", "backend", 85, ["springboot", "spring"]),
    ("Spring Security", "backend", 45, []),
    ("Spring Cloud", "backend", 35, ["spring cloud gateway", "eureka", "feign"]),
    ("Spring Data", "backend", 35, ["spring data mongodb"]),
    ("Spring Batch", "backend", 25, []),
    ("Spring WebFlux", "backend", 25, ["webflux", "project reactor"]),
    ("Spring Boot Actuator", "backend", 20, ["actuator"]),
    ("Quarkus", "backend", 35, []),
    ("Micronaut", "backend", 15, []),
    ("Jakarta EE", "backend", 30, ["java ee", "j2ee", "jee"]),
    ("JPA", "backend", 60, ["spring data jpa", "jakarta persistence", "jpa/hibernate", "jpa hibernate"]),
    ("Hibernate", "backend", 50, []),
    ("JDBC", "backend", 25, []),
    ("Maven", "ferramenta", 45, []),
    ("Gradle", "ferramenta", 35, []),
    ("Lombok", "backend", 20, []),
    ("GraalVM", "backend", 15, ["mandrel", "native image"]),
    ("Django", "backend", 70, []),
    ("Django REST Framework", "backend", 35, ["drf"]),
    ("Flask", "backend", 55, []),
    ("FastAPI", "backend", 60, []),
    ("SQLAlchemy", "backend", 25, []),
    ("Laravel", "backend", 60, []),
    ("Symfony", "backend", 20, []),
    ("Rails", "backend", 45, ["ruby on rails"]),
    (".NET", "backend", 70, ["dotnet", "net core", ".net 8"]),
    ("ASP.NET", "backend", 50, ["asp.net core", "asp net core", "asp.net mvc"]),
    ("Entity Framework", "backend", 35, ["ef core", "entity framework core"]),
    ("Prisma", "backend", 30, []),
    ("TypeORM", "backend", 20, []),
    ("Sequelize", "backend", 20, []),
    ("Mongoose", "backend", 20, []),
    ("REST", "arquitetura", 85, ["rest api", "api rest", "restful", "apis rest"]),
    ("OpenAPI", "arquitetura", 40, ["swagger", "openapi/swagger"]),
    ("GraphQL", "arquitetura", 50, ["apollo"]),
    ("gRPC", "arquitetura", 35, []),
    ("SOAP", "arquitetura", 25, ["wsdl"]),
    ("WebSocket", "arquitetura", 40, ["websockets", "socket.io"]),
    ("Tomcat", "backend", 20, ["apache tomcat"]),
    ("WildFly", "backend", 15, ["jboss"]),
    ("WebLogic", "backend", 15, ["oracle weblogic"]),
    # ── Mensageria e eventos ──────────────────────────────────────────────
    ("Kafka", "dados", 55, ["apache kafka", "kafka streams"]),
    ("RabbitMQ", "dados", 45, ["rabbit"]),
    ("ActiveMQ", "dados", 20, ["artemis", "activemq artemis", "amq"]),
    ("JMS", "dados", 20, ["java message service"]),
    ("AMQP", "dados", 15, []),
    ("AWS SQS", "cloud", 30, ["sqs", "amazon sqs"]),
    ("AWS SNS", "cloud", 20, ["sns", "amazon sns"]),
    ("Arquitetura orientada a eventos", "arquitetura", 40, ["eda", "event-driven", "event driven architecture", "event driven"]),
    # ── Bancos de dados ───────────────────────────────────────────────────
    ("PostgreSQL", "banco", 85, ["postgres", "psql", "pg"]),
    ("MySQL", "banco", 80, []),
    ("MariaDB", "banco", 25, []),
    ("SQL Server", "banco", 60, ["sqlserver", "mssql"]),
    ("Oracle", "banco", 50, ["oracle db", "oracle database"]),
    ("MongoDB", "banco", 70, ["mongo"]),
    ("Redis", "banco", 60, []),
    ("Elasticsearch", "banco", 40, ["elastic", "opensearch"]),
    ("Cassandra", "banco", 20, ["apache cassandra"]),
    ("DynamoDB", "banco", 30, ["amazon dynamodb"]),
    ("SQLite", "banco", 25, []),
    ("Firebase", "banco", 35, ["firestore", "firebase realtime database"]),
    ("Supabase", "banco", 20, []),
    ("Neo4j", "banco", 15, []),
    ("Modelagem de dados", "dados", 55, ["modelagem", "data modeling", "er"]),
    ("Tuning de queries", "banco", 25, ["query tuning", "otimizacao de queries", "performance de queries"]),
    # ── Dados e IA ────────────────────────────────────────────────────────
    ("ETL", "dados", 45, ["pipeline de dados", "data pipeline", "elt"]),
    ("Power BI", "dados", 45, ["powerbi"]),
    ("Tableau", "dados", 25, []),
    ("Excel", "ferramenta", 40, ["excel avancado", "planilhas"]),
    ("Pandas", "dados", 50, []),
    ("NumPy", "dados", 35, []),
    ("Spark", "dados", 35, ["apache spark", "pyspark"]),
    ("Airflow", "dados", 30, ["apache airflow"]),
    ("dbt", "dados", 25, []),
    ("Databricks", "dados", 30, []),
    ("Snowflake", "dados", 25, []),
    ("BigQuery", "dados", 25, ["google bigquery"]),
    ("Hadoop", "dados", 15, ["hdfs", "hive"]),
    ("Machine Learning", "ia", 50, ["ml", "aprendizado de maquina"]),
    ("Deep Learning", "ia", 30, ["redes neurais", "neural networks"]),
    ("scikit-learn", "ia", 30, ["sklearn"]),
    ("TensorFlow", "ia", 30, ["keras"]),
    ("PyTorch", "ia", 30, []),
    ("LLM", "ia", 40, ["llms", "genai", "ia generativa", "openai", "large language models"]),
    ("LangChain", "ia", 25, []),
    ("RAG", "ia", 25, ["retrieval augmented generation"]),
    ("Engenharia de prompt", "ia", 25, ["prompt engineering"]),
    ("Visão computacional", "ia", 15, ["computer vision", "opencv"]),
    ("NLP", "ia", 20, ["processamento de linguagem natural"]),
    # ── Cloud ─────────────────────────────────────────────────────────────
    ("AWS", "cloud", 80, ["amazon web services"]),
    ("AWS Lambda", "cloud", 45, ["lambda", "lambdas", "aws lambdas"]),
    ("AWS EC2", "cloud", 35, ["ec2", "amazon ec2"]),
    ("AWS S3", "cloud", 35, ["s3", "amazon s3"]),
    ("AWS ECS", "cloud", 20, ["ecs", "fargate"]),
    ("AWS EKS", "cloud", 20, ["eks"]),
    ("AWS RDS", "cloud", 20, ["rds", "aurora"]),
    ("API Gateway", "cloud", 25, ["aws api gateway"]),
    ("CloudWatch", "cloud", 20, ["aws cloudwatch"]),
    ("Azure", "cloud", 60, ["microsoft azure"]),
    ("Azure Functions", "cloud", 20, []),
    ("Azure API Management", "cloud", 15, ["apim", "azure apim"]),
    ("Google Cloud", "cloud", 45, ["gcp", "google cloud platform"]),
    ("Cloud Functions", "cloud", 15, ["google cloud functions"]),
    ("Serverless", "cloud", 30, ["serverless framework"]),
    ("Oracle Cloud", "cloud", 15, ["oci", "oracle cloud infrastructure"]),
    # ── Infra, entrega e observabilidade ──────────────────────────────────
    ("Docker", "devops", 85, ["containers", "docker compose"]),
    ("Kubernetes", "devops", 60, ["k8s", "kube"]),
    ("OpenShift", "devops", 30, ["ocp", "openshift container platform"]),
    ("Helm", "devops", 25, []),
    ("CI/CD", "devops", 75, ["ci cd", "integracao continua", "entrega continua", "pipeline", "pipelines"]),
    ("GitHub Actions", "devops", 55, ["gh actions"]),
    ("GitLab CI", "devops", 30, ["gitlab ci/cd"]),
    ("Jenkins", "devops", 40, ["jenkins pipelines", "jenkinsfile"]),
    ("Azure DevOps", "devops", 35, ["vsts", "tfs", "azure pipelines"]),
    ("ArgoCD", "devops", 20, ["argo cd", "gitops"]),
    ("Terraform", "devops", 45, ["iac"]),
    ("Ansible", "devops", 25, []),
    ("Linux", "devops", 70, ["unix", "ubuntu", "debian"]),
    ("Nginx", "devops", 45, []),
    ("Observabilidade", "devops", 40, ["monitoramento", "observability"]),
    ("Datadog", "devops", 30, []),
    ("Grafana", "devops", 30, []),
    ("Prometheus", "devops", 30, []),
    ("Dynatrace", "devops", 20, []),
    ("New Relic", "devops", 15, ["newrelic"]),
    ("ELK", "devops", 25, ["elk stack", "kibana", "logstash", "elastic stack"]),
    ("Splunk", "devops", 15, []),
    ("OpenTelemetry", "devops", 20, ["otel"]),
    ("Micrometer", "devops", 15, []),
    ("SRE", "devops", 25, ["site reliability engineering"]),
    ("Alta disponibilidade", "arquitetura", 25, ["high availability", "sistemas criticos", "missao critica"]),
    ("SonarQube", "ferramenta", 30, ["sonar", "sonarcloud"]),
    # ── Qualidade e testes ────────────────────────────────────────────────
    ("Testes automatizados", "testes", 70, ["testes", "test", "qa", "e2e", "testes de integracao"]),
    ("Testes unitários", "testes", 55, ["unit tests", "unit testing", "teste unitario"]),
    ("TDD", "testes", 35, ["test driven development"]),
    ("BDD", "testes", 20, ["cucumber", "behavior driven development"]),
    ("JUnit", "testes", 45, ["junit 5"]),
    ("Mockito", "testes", 35, []),
    ("Testcontainers", "testes", 20, []),
    ("Jest", "testes", 50, []),
    ("Vitest", "testes", 20, []),
    ("Cypress", "testes", 40, []),
    ("Playwright", "testes", 30, []),
    ("Selenium", "testes", 35, ["selenium webdriver"]),
    ("Pytest", "testes", 40, []),
    ("Postman", "ferramenta", 40, ["insomnia"]),
    ("JMeter", "testes", 15, ["testes de carga", "k6"]),
    # ── Arquitetura e ofício ──────────────────────────────────────────────
    ("Git", "ferramenta", 90, ["controle de versao"]),
    ("GitHub", "ferramenta", 60, []),
    ("GitLab", "ferramenta", 30, []),
    ("Bitbucket", "ferramenta", 20, []),
    ("GitFlow", "metodologia", 25, ["git flow", "trunk based", "trunk-based development", "branching"]),
    ("Arquitetura de software", "arquitetura", 65, ["arquitetura", "system design"]),
    ("Microsserviços", "arquitetura", 55, ["microservices", "microservicos", "arquitetura de microsservicos"]),
    ("Arquitetura hexagonal", "arquitetura", 30, ["hexagonal", "ports and adapters", "clean architecture", "arquitetura limpa"]),
    ("Arquitetura em camadas", "arquitetura", 20, ["layered architecture", "mvc"]),
    ("DDD", "arquitetura", 35, ["domain driven design", "domain-driven design"]),
    ("Design Patterns", "arquitetura", 40, ["padroes de projeto", "design pattern", "gof"]),
    ("Clean Code", "metodologia", 45, ["codigo limpo"]),
    ("SOLID", "metodologia", 40, ["principios solid"]),
    ("Algoritmos", "metodologia", 55, ["estrutura de dados", "algoritmos e estruturas de dados"]),
    ("Code review", "metodologia", 45, ["revisao de codigo", "pull request review"]),
    ("Programação reativa", "arquitetura", 20, ["reactive programming", "reativo"]),
    ("Integração de sistemas", "arquitetura", 25, ["integracao com erp", "integracoes", "edi"]),
    ("Processamento em lote", "dados", 20, ["batch", "processamento batch", "sftp", "xml em lote"]),
    # ── Agilidade e gestão ────────────────────────────────────────────────
    ("Scrum", "metodologia", 60, ["dailies", "sprints", "sprint review"]),
    ("Kanban", "metodologia", 40, []),
    ("Metodologias ágeis", "metodologia", 50, ["agile", "agil", "metodologias ageis", "agilidade"]),
    ("Jira", "ferramenta", 45, ["jira software"]),
    ("Confluence", "ferramenta", 20, []),
    # ── Segurança e identidade ────────────────────────────────────────────
    ("Segurança", "seguranca", 45, ["security", "appsec", "seguranca da informacao"]),
    ("OWASP", "seguranca", 30, ["owasp top 10"]),
    ("OAuth 2.0", "seguranca", 35, ["oauth", "oauth2", "openid connect", "oidc"]),
    ("JWT", "seguranca", 35, ["json web token"]),
    ("Keycloak", "seguranca", 25, []),
    ("LGPD", "seguranca", 20, []),
    # ── Mobile ────────────────────────────────────────────────────────────
    ("React Native", "mobile", 50, ["react-native"]),
    ("Flutter", "mobile", 45, []),
    ("Android", "mobile", 45, []),
    ("iOS", "mobile", 40, []),
    ("SwiftUI", "mobile", 25, []),
    ("Jetpack Compose", "mobile", 20, []),
    # ── Domínio de negócio ────────────────────────────────────────────────
    ("Bancário e financeiro", "dominio", 40, ["bancario", "financeiro", "fintech", "banking", "mercado financeiro", "segmento bancario"]),
    ("Meios de pagamento", "dominio", 25, ["pagamentos", "payments", "pix", "adquirencia"]),
    ("Seguros", "dominio", 20, ["insurtech"]),
    ("Varejo", "dominio", 25, ["retail", "franquias", "pdv", "ponto de venda", "cupom fiscal"]),
    ("E-commerce", "dominio", 30, ["ecommerce", "comercio eletronico", "marketplace"]),
    ("Saúde", "dominio", 20, ["healthtech"]),
    ("Logística", "dominio", 15, ["supply chain"]),
    ("Educação", "dominio", 15, ["edtech"]),
    ("Telecom", "dominio", 15, ["telecomunicacoes"]),
    ("Setor público", "dominio", 15, ["governo", "govtech"]),
    ("ERP", "dominio", 20, ["sap", "totvs"]),
    # ── Idiomas ───────────────────────────────────────────────────────────
    ("Inglês", "idioma", 80, ["english"]),
    ("Espanhol", "idioma", 40, ["spanish"]),
]


def seed_rows() -> list[dict]:
    from app.services.tag_catalog import CATEGORY_COLORS, slugify

    return [
        {
            "slug": slugify(name),
            "name": name,
            "category": category,
            "color": CATEGORY_COLORS.get(category),
            "aliases": aliases,
            "popularity": popularity,
        }
        for name, category, popularity, aliases in SEED
    ]
